services:
  api:
    image: ${IMAGE_TAG}
    restart: unless-stopped
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_ROUTER}.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.${TRAEFIK_ROUTER}.entrypoints=web"
      - "traefik.http.services.${TRAEFIK_ROUTER}.loadbalancer.server.port=8000"
    env_file: .env

networks:
  traefik-public:
    external: true
